### PR TITLE
Add Chromium for Mac ARM

### PR DESCRIPTION
**Pull request by beaufortfrancois**
FIX https://github.com/beaufortfrancois/download-chromium/issues/70

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
@paulirish Can you review?

**Review by paulirish — APPROVED** [review]
lg!

**Comment by core-code** [comment]
can i make two remarks?

• going to https://download-chromium.appspot.com i don't see the build listed anywhere, there is just a link to the Intel version. is this supposed to only present the 'native' version and make it impossible to download builds for other architectures?

• the ARM build doesn't seem properly signed
```
spctl --assess --type execute --verbose /Users/cc/Desktop/Chromium.app
Users/cc/Desktop/Chromium.app: code has no resources but signature indicates they must be present
```

**Comment by connorjclark** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1231936

Until above is resolved, should probably revert this PR.

**Comment by core-code** [comment]
this is what i mentioned above: "the ARM build doesn't seem properly signed"

**Pull request merged**
