### PR TITLE
Add support for continuous builds

### PR DESCRIPTION
**Pull request by beaufortfrancois**
As suggested, here's the PR that adds support for continuous builds.

R=@paulirish
FIX=#8

screenshot 2015-11-24 at 4 49 30 pm

### CODE REVIEW

**Comment by paulirish** [comment]
tbh i have trouble keeping "continuous" and "snapshot" differentiated, can we use slightly different text?

how about… "latest" , "last known good revision"

**Comment by beaufortfrancois** [comment]
Sure. I'll rename them tomorrow.

**Comment by beaufortfrancois** [comment]
Updated! @paulirish 

screenshot 2015-11-25 at 11 09 44 am

**Comment by paulirish** [comment]
lgtm

**Comment by beaufortfrancois** [comment]
Do you want me to update live site?

**Comment by beaufortfrancois** [comment]
Here it is!
https://download-chromium.appspot.com/?platform=Android&type=continuous

**Pull request merged**
