### PR TITLE
Added Windows x64 support

### PR DESCRIPTION
**Pull request by phistuck**
Windows x64 builds seem to exist and seem up to date.
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/

### CODE REVIEW

**Comment by phistuck** [comment]
Fixes https://github.com/beaufortfrancois/download-chromium/issues/15.

**Comment by paulirish** [comment]
@beaufortfrancois for the review

**Comment by beaufortfrancois** [comment]
Thank you @phistuck!
See https://github.com/beaufortfrancois/download-chromium/pull/34

**Comment by beaufortfrancois** [comment]
It is live at https://download-chromium.appspot.com/?platform=Win_x64&type=snapshots

**Pull request merged**
